services:
  # Service pour le backend Django
  - type: web
    name: alloriginal-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    # Ajustez en fonction de vos besoins pour un plan payant
    # plan: standard
    buildCommand: echo "Build inclus dans le Dockerfile"
    startCommand: ""
    envVars:
      - key: DEBUG
        value: "false"
      - key: APPLY_MIGRATIONS
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://alloriginal-frontend.onrender.com"
      - key: DB_NAME
        fromDatabase:
          name: alloriginal-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: alloriginal-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: alloriginal-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: alloriginal-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: alloriginal-db
          property: port

# Base de données PostgreSQL
databases:
  - name: alloriginal-db
    plan: starter # Adaptez selon vos besoins
    databaseName: alloriginal_db
