# Generated by Django 5.2 on 2025-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Spécification', 'verbose_name_plural': 'Spécifications'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Générique', max_length=100, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='En stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancien prix'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='En promotion'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Spécification mise en avant'),
        ),
    ]
