# Generated by Django 5.2 on 2025-05-04 17:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_specificationtype_remove_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name="Nom de l'auteur")),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email de l'auteur")),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name="Titre de l'avis")),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Achat vérifié')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Légende')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.review', verbose_name='Avis')),
            ],
            options={
                'verbose_name': "Image d'avis",
                'verbose_name_plural': "Images d'avis",
            },
        ),
    ]
