# Generated by Django 5.2 on 2025-05-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
